/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tree(props) {
  const { nodes, materials } = useGLTF('/tree.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Pine_4m.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.05} />
    </group>
  )
}

useGLTF.preload('/tree.glb')
